video: tegra: host: fix unused function build issue
Fix build issue pointed out by clang

nvhost_intr.c:53:20: error: unused function 'nvhost_intr_is_virtual_dev'
isp.c:211:19: error: unused function 'tegra_isp_read'
isp.c:216:20: error: unused function 'tegra_isp_write'

bug 1745660

Change-Id: I3d6835aef899ad7a175cdc4dba6cafd34dbfeabd
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1152554
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: Shridhar Rasal <srasal@nvidia.com>