mmc: mmc_test: add mmc_test_prepare_mrq() definition
Call to the function mmc_test_prepare_sbc() got removed as
part of the commit 'e9bb736568fd0caeee7a625f8d784e817f093cfb'
from the function mmc_test_prepare_mrq() definition leading to
below compilation error when CONFIG_MMC_TEST enabled.
"""
CC      drivers/mmc/card/mmc_test.o
/media/Linx3/stage-main/daily/0688/drive-oss-src/kernel/drivers/mmc/card/mmc_test.c:194:13:
error: 'mmc_test_prepare_sbc' defined but not used [-Werror=unused-function]
static void mmc_test_prepare_sbc(struct mmc_test_card *test,
"""

Hence, add mmc_test_prepare_mrq() definition in mmc_test.c itself.

Bug 1805138

Change-Id: Ie334b1924127e09ce807341eebbe86f1e4bce292
Signed-off-by: R Raj Kumar <rrajk@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1620308
GVS: Gerrit_Virtual_Submit
Reviewed-by: Venu Byravarasu <vbyravarasu@nvidia.com>
Reviewed-by: Pavan Kunapuli <pkunapuli@nvidia.com>
Tested-by: Pavan Kunapuli <pkunapuli@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>