misc: tegra-profiler: fix build error
Fix build error on arm platforms.
This patch fixes the following build error:

armv7_pmu.c: In function 'quadd_armv7_pmu_init_for_cpu':
armv7_pmu.c:789:9: error: incompatible types when assigning
to type 'long unsigned int' from type 'struct cpu'

Bug 1855750

Change-Id: Ic83dd012df9edef7c8a0507e30038e26207740fc
Signed-off-by: Igor Nabirushkin <inabirushkin@nvidia.com>
Reviewed-on: http://git-master/r/1275021
(cherry picked from commit 41bc9c10783c466da08a0bb5c57b9ba771e5c039)