Revert "t19x: enable smmu for nvdla0 and nvdla1"
This reverts commit 6a1050a00c495ee5967b3e459556287a16087a36.

This patch triggers compilation errors on simulation:
kernel-dts/tegra194-soc/tegra194-soc-base.dtsi:28:49: fatal error: dt-bindings/memory/tegra194-swgroup.h: No such file or directory
 #include <dt-bindings/memory/tegra194-swgroup.h>

Hence revert the change for now

Change-Id: I515218dc8e031db71aa3bae27972a4540e36bcfc
Reviewed-on: http://git-master/r/1269298
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Deepak Nibade <dnibade@nvidia.com>
Tested-by: Deepak Nibade <dnibade@nvidia.com>