misc: tegra-profiler: fix compilation issue
Fix below compilation issue.

dwarf_unwind.c:2044:1: error: stack frame size of 2080 bytes in
function 'quadd_get_user_cc_dwarf' [-Werror,-Wframe-larger-than=]

bug 1745660

Change-Id: I1b30ff58a1f636a2f0fe4160d0141a3bdf268675
Signed-off-by: Igor Nabirushkin <inabirushkin@nvidia.com>
Reviewed-on: http://git-master/r/1150392
(cherry picked from commit d6d1ea3981fe972c4bd26b4037268ce9399c025a)