clk: tegra: TEGRA_CLK_DEBUG depends on DEBUG_FS
fix below build error by setting correct dependency of
CONFIG_TEGRA_CLK_DEBUG configuration.

clk.c: In function 'tegra_register_debugfs':
clk.c:518:3: error: implicit declaration of function
'__clk_debugfs_add_file' [-Werror=implicit-function-declaration]
  d = __clk_debugfs_add_file(clk, "clk_update_rate", 0200, clk,
  ^
clk.c:518:5: warning: assignment makes pointer from integer
without a cast
  d = __clk_debugfs_add_file(clk, "clk_update_rate", 0200, clk,
    ^
clk.c:523:5: warning: assignment makes pointer from integer
without a cast
  d = __clk_debugfs_add_file(clk, "clk_update_state", 0200, clk,
    ^
clk.c:528:5: warning: assignment makes pointer from integer
without a cast
   d = __clk_debugfs_add_file(clk, "clk_update_parent", 0200, clk,
     ^
cc1: some warnings being treated as errors
make[5]: *** [drivers/clk/tegra/clk.o] Error 1
make[4]: *** [drivers/clk/tegra] Error 2
make[3]: *** [drivers/clk] Error 2
make[2]: *** [drivers] Error 2

Bug 1778001

Change-Id: I10de7d11320ae7885f8b94b468ad98f87dfe2328
Signed-off-by: David Pu <dpu@nvidia.com>
(cherry picked from commit f68ebca0de69f3377f151e3cd616368f23a10c12)
Reviewed-on: https://git-master.nvidia.com/r/1551323
Reviewed-by: Peter De Schrijver <pdeschrijver@nvidia.com>
Tested-by: Peter De Schrijver <pdeschrijver@nvidia.com>
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: svccoveritychecker <svccoveritychecker@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: Timo Alho <talho@nvidia.com>