cpuidle: include header cpuhotplug.h
L4T uses a different compiler version for modular kernel only build
(where no issues is seen) and external build which is not protected
per-virtual on dev-kernel.

The build failure is as follows:


error: implicit declaration of function â€˜cpuhp_setup_stateâ€™
[-Werror=implicit-function-declaration]
err = cpuhp_setup_state(CPUHP_AP_ONLINE_DYN,
        ^
error: â€˜CPUHP_AP_ONLINE_DYNâ€™ undeclared (first use in this function)
err = cpuhp_setup_state(CPUHP_AP_ONLINE_DYN,
                                  ^
                                  
The fix is to include linux/cpuhotplug.h which consists of all the APIs
and macros related to cpu hotplug.

Bug 2130554

Change-Id: I6a174d9130ed00930a75c74cf3417cfe5e593abf
Signed-off-by: Ajay Nandakumar <anandakumarm@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1722880
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>