net: ipv6: remove unused variable in rt6_get_route_info()
Due to unused variable, compilation fails with error:
 net/ipv6/route.c:2344:6: error: unused variable 'ifindex' [-Werror=unused-variable]
   int ifindex = dev->ifindex;

The veriable seems to be unused regardless of config options so just
remove it

Change-Id: I169a29d9b8f9857d02d941a29cedc9a449921daf
Signed-off-by: Timo Alho <talho@nvidia.com>