memory: tegra: Remove IS_ERR_VALUE on int type
There are some build errors when compiling tegra210-emc:
1)drivers/memory/tegra/tegra210-emc.c:
       In function 'tegra210_emc_predict_parent':
  include/linux/err.h:21:49: error:
       cast to pointer from integer of different size
  #define IS_ERR_VALUE(x) \
       unlikely((unsigned long)(void *)(x) >= (unsigned long)-MAX_ERRNO)
  [ There are quite a few this type of errors in other functions too. ]

2)drivers/memory/tegra/tegra210-emc.c: In function 'dram_temp_get':
  drivers/memory/tegra/tegra210-emc.c:1067:7: error:
       'temp' may be used uninitialized in this function

So this patch removes all IS_ERR_VALUE when the value is int type.
And it fixes the 2nd error by initializing it.

Bug 1874686

Change-Id: I6cdb35d7c8886df8ee8a8d64eed0b0333f0d5976
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1564134
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Peter De Schrijver <pdeschrijver@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>