soc/tegra: pm-tegra210: fix build error
This patch fixes below error as tv64 is removed since Kernel 4.10:
    In file included from drivers/soc/tegra/pm-tegra210.c:17:0:
    drivers/soc/tegra/pm-tegra210.c: In function ‘idle_write’:
    drivers/soc/tegra/pm-tegra210.c:404:56: error:
    	request for member ‘tv64’ in something not a structure or union

Bug 200419967

Change-Id: I20060d8126aee91926224677b282decfabdb38bc
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1749214
GVS: Gerrit_Virtual_Submit
Reviewed-by: Joseph Lo <josephl@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>