drivers: platform: tegra: Add bootloader drivers
This is the patch to import initial bootloader drivers added
by Ishan Mittal <imittal@nvidia.com> in K4.4.

It also squashed the commit 5af516354b63 ("coverity: Fix the
error reported by Coverity") since it removed two iounmap()
calls that were originally added in the initial patch.

Meanwhile, fixing below warnings and errors from checkpatch:
 WARNING: Prefer seq_puts to seq_printf
 #111: FILE: drivers/platform/tegra/tegra_bootloader_debug.c:80:
 +		seq_printf(s, "Error mapping profiling data\n");
 #149: FILE: drivers/platform/tegra/tegra_bootloader_debug.c:118:
 +		seq_printf(s, "Error mapping bootloader debug data\n");

 ERROR: do not initialise globals to 0
 #322: FILE: drivers/platform/tegra/tegra_bootloader_debug_init.c:25:
 +phys_addr_t tegra_bl_debug_data_start = 0;
 #325: FILE: drivers/platform/tegra/tegra_bootloader_debug_init.c:28:
 +phys_addr_t tegra_bl_debug_data_size = 0;
 #328: FILE: drivers/platform/tegra/tegra_bootloader_debug_init.c:31:
 +phys_addr_t tegra_bl_prof_start = 0;
 #331: FILE: drivers/platform/tegra/tegra_bootloader_debug_init.c:34:
 +phys_addr_t tegra_bl_prof_size = 0;

Bug 200416198

Change-Id: I29f9f4d59d0c9eeacc85e8e07b28cb56406a1936
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1773317
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>