trusty: fix link errors when being selected as =m
ERROR: "trusty_call32_mem_buf"
[drivers/trusty/trusty-virtio.ko] undefined!
ERROR: "is_trusty_dev_enabled"
[drivers/trusty/trusty-otf-iface.ko] undefined!

So this patch exports these two functions to fix it.

Bug 200305192

Change-Id: Iee97a708e525114a5e749777b306ae0ce05cbb1b
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: http://git-master/r/1475903
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>