video: tegra: dc: fix unused function build issue
Fix the following build issues found by clang

dc.c:3227:20: error: unused function 'enable_dc_irq'
window.c:350:20: error: unused function 'tegra_dc_update_scaling'
hdmihdcp.c:322:19: error: unused function 'get_an'
hdmihdcp.c:339:19: error: unused function 'get_aksv'                  ^
hdmihdcp.c:348:20: error: unused function 'set_bksv'
hdmi2.0.c:132:20: error: unused function 'tegra_hdmi_irq_enable'
hdmi2.0.c:140:20: error: unused function 'tegra_hdmi_irq_disable'                   ^
hdmi2.0.c:148:20: error: unused function 'tegra_hdmi_hpd_asserted'
hdmi2.0.c:2055:19: error: unused function 'tegra_hdmi_get_shift_clk_div'

bug 1745660

Change-Id: I70e2f44cf23b46596bac265f01ee20188cfe9721
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1152553
GVS: Gerrit_Virtual_Submit
Reviewed-by: Mitch Luban <mluban@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>