input: input-cfboost: Include linux/sched/types.h
There is a build error when compiling the driver with K4.14:
    drivers/input/input-cfboost.c: In function ‘cfboost_init’:
    drivers/input/input-cfboost.c:303:9: error:
    	variable ‘sparm’ has initializer but incomplete type
    struct sched_param sparm = {
    	   ^~~~~~~~~~~

So this patch adds the corresponding header file to fix it.

Bug 200425329

Change-Id: Idd3caabeb7c8ef3985a05ec5008f8605981c6900
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1770000
Reviewed-by: svc-mobile-coverity <svc-mobile-coverity@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>