platform: tegra: add support combined UART for fiq_enable()
This patch adds combined UART support for fiq_enable().
Must add "console-port" & "combined-uart" into combined-uart node. That
for tegra_fiq_debugger to know using combined uart.

combined-uart {
	console-port;
	combined-uart;
	status = "okay";
};

Bug 2041165

[ The cherry-pick also fixes errors/warnings reported by checkpatch:
    WARNING: line over 80 characters
    #60: FILE: drivers/platform/tegra/tegra_fiq_debugger.c:143:
    +#define CONSOLE_WRITE (CONSOLE_RING_DOORBELL | CONSOLE_FLUSH_DATA_TO_PORT)

    WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
    #70: FILE: drivers/platform/tegra/tegra_fiq_debugger.c:153:
    +	unsigned val;

    ERROR: space required before the open parenthesis '('
    #73: FILE: drivers/platform/tegra/tegra_fiq_debugger.c:156:
    +	while(__raw_readl(t->debug_port_base) & CONSOLE_IS_BUSY);

    ERROR: trailing statements should be on next line
    #73: FILE: drivers/platform/tegra/tegra_fiq_debugger.c:156:
    +	while(__raw_readl(t->debug_port_base) & CONSOLE_IS_BUSY);

    WARNING: line over 80 characters
    #80: FILE: drivers/platform/tegra/tegra_fiq_debugger.c:163:
    +static void combined_fiq_enable(struct platform_device *pdev...
]

Bug 200416212

Change-Id: Ia1acec1b72d37c33f50cdc934475a874889d404a
Signed-off-by: steven kao <skao@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1628667
(cherry picked from commit 068216f17ff010369b6f07778cdeeca012a5e149)
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1750502
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>