arm64: add explicit cast to int in field extraction
The lack of an explicit typecast in a ternary conditional produces the
following compiler message with -Werror, so add an explicit cast to int
because the value ends up being used as an int anyway:

include/asm/cpufeature.h: In function 'cpuid_feature_extract_field':
include/asm/cpufeature.h:161:55: error: signed and unsigned type in conditional expression [-Werror=sign-compare]

Bug 1853519

Change-Id: Ie5eec42b7f1302883beace3ae03e4e217af10b1a
Signed-off-by: Konsta Holtta <kholtta@nvidia.com>
Reviewed-on: http://git-master/r/1327687
Reviewed-by: Timo Alho <talho@nvidia.com>
Reviewed-by: Mikko Perttunen <mperttunen@nvidia.com>
GVS: Gerrit_Virtual_Submit