video: tegra: dc: remove unused variable
To avoid build warning and error, remove the unused variable.

/***
  ^
dc.c: In function 'tegra_dc_probe':
dc.c:4301:25: error: unused variable 'partition_id_disb' [-Werror=unused-variable]
  int partition_id_disa, partition_id_disb;
                         ^
dc.c:4301:6: error: unused variable 'partition_id_disa' [-Werror=unused-variable]
  int partition_id_disa, partition_id_disb;
      ^
  CC      drivers/video/tegra/nvmap/nvmap_dev.o
***/

Change-Id: If3f8460aa6835b2d92838b44906343687e96aca2
Signed-off-by: Laxman Dewangan <ldewangan@nvidia.com>
Reviewed-on: http://git-master/r/757660
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Animesh Kishore <ankishore@nvidia.com>
Reviewed-by: Bharat Nihalani <bnihalani@nvidia.com>