host: nvhost: fix the sparse warnings
Fixed the following sparse warnings by adding the '__user' cast
to user space pointers, this will notify the sparse that they are
user space pointer. Hence, remove the sparse error and warnings.

- bus_client.c:905:51: warning: incorrect type in argument 4
- bus_client.c:905:60: warning: incorrect type in argument 5
- host1x.c:325:51: warning: incorrect type in argument 4
- host1x.c:325:60: warning: incorrect type in argument 5
- vhost.c:231:43: warning: incorrect type in argument 2
- vhost.c:238:51: warning: cast removes address space of expression
- vhost.c:238:51: warning: incorrect type in argument 2
- vhost.c:254:35: warning: cast removes address space of expression
- vhost.c:254:35: warning: incorrect type in argument 1
- vhost.c:211:5: error: symbol 'vhost_rdwr_module_regs' redeclared
                 with different type (originally declared at - vhost.h:52)
                 - incompatible argument 4 (different address spaces)

Bug 200067946
Bug 200088648

Change-Id: Ib9b8172fa9aeea4e1be061d8d43c4a029a72aeb0
Signed-off-by: Amit Sharma (SW-TEGRA) <amisharma@nvidia.com>
Reviewed-on: http://git-master/r/742685
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Peter Daifuku <pdaifuku@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-on: http://git-master/r/757051