platform: nvadsp: fix unused function build issue
Fix below issue found while compiling kernel with clang

acast.c:75:19: error: unused function 'acast_read'

bug 1745660

Change-Id: I9d61c87328294024b53ffd49b7bea81112059451
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1150422
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Nitin Kumbhar <nkumbhar@nvidia.com>