nvidia: Preventing vi/ folder to be compiled
drivers/video/tegra/host/vi is getting compiled
unneccesarily which is leading to these errors

drivers/built-in.o:(.data+0xee110): undefined reference to `t18_vi_info'
18382: drivers/built-in.o:(.data+0xee1e0): undefined reference to `t18_vi_info'
18383: drivers/built-in.o:(.data+0xee1e8): undefined reference to `vi4_fops

Bug 200295104

Change-Id: Ifa3d32cc2a94d80b842d8ee021dba11a7826f8cc
Signed-off-by: Ishan Mittal <imittal@nvidia.com>
Reviewed-on: http://git-master/r/1496794
GVS: Gerrit_Virtual_Submit
Tested-by: Amar Agrawal <amara@nvidia.com>
Reviewed-by: Amar Agrawal <amara@nvidia.com>