video: tegra: dc: fix gcc 7.3 l4t build
Fix below l4t build errors with gcc 7.3:
$TOP/kernel/nvidia/drivers/video/tegra/dc/dc.c: In function
‘tegra_dc_probe’:8$6]
$TOP/kernel/nvidia/drivers/video/tegra/dc/dc.c:6448:44: error:
‘of_fb_res.start6]
’ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
  fb_mem->start = (resource_size_t)of_fb_res.start;
                                   ~~~~~~~~~^~~~~~
$TOP/kernel/nvidia/drivers/video/tegra/dc/dc.c:6449:42: error:
‘of_fb_res.end▒T=$▒ may be used uninitialized in this function
[-Werror=maybe-uninitialized]
  fb_mem->end = (resource_size_t)of_fb_res.end;
                                 ~~~~~~~~~^~~~
cc1: all warnings being treated as errors

bug 200433410

Change-Id: Ibe5fe52f121389b5ca7392ab6d76cd67057700d5
Signed-off-by: Bitan Biswas <bbiswas@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1783722
(cherry picked from commit a06cf3cec4c2e9722d99bd91fff634e3f1a2de1a from dev-kernel)
Reviewed-on: https://git-master.nvidia.com/r/1810788
Reviewed-by: Stephen Warren <swarren@nvidia.com>
Reviewed-by: Amulya Yarlagadda <ayarlagadda@nvidia.com>
Tested-by: Amulya Yarlagadda <ayarlagadda@nvidia.com>