adma: tegra: fix unused function build issue
fix below compilation issue pointed by clang

tegra18x-adma.c:41:19: error: unused function 'adast_read'

bug 1745660

Change-Id: Ia9a5ce8ea3309e8441d6174a1818876d575cddc7
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1150419
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Nitin Kumbhar <nkumbhar@nvidia.com>