gpu: nvgpu: Fix build failure by missing headers
Forward declare struct file & inode

../../../nvgpu/drivers/gpu/nvgpu/gk20a/fecs_trace_gk20a.c:26:0:
../../../nvgpu/drivers/gpu/nvgpu/gk20a/ctxsw_trace_gk20a.h:29:57:
 error: 'struct file' declared inside parameter list [-Werror]
int gk20a_ctxsw_dev_release(struct inode *inode, struct file *filp);

Bug 200310575

Change-Id: I872b3a2483fb4dda9569aca1b4729bcd8acd5968
Signed-off-by: skadamati <skadamati@nvidia.com>
Reviewed-on: http://git-master/r/1490166
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Terje Bergstrom <tbergstrom@nvidia.com>
Reviewed-by: Alex Waterman <alexw@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sumeet Gupta <sumeetg@nvidia.com>