trusty: use #if IS_ENABLED() instead of #ifdef
The CONFIG_TRUSTY could be selected as a module while should
still work for trusty driver.

Prior to this patch, there're compile errors when selecting
CONFIG_TRUSTY=m:

drivers/trusty/trusty.c:93:5: error: redefinition of 'trusty_fast_call32'
drivers/trusty/trusty.c:109:5: error: redefinition of 'trusty_fast_call64'

So this patch just changes the "#ifdef" to "#if IS_ENABLED".

Bug 200305192

Change-Id: I867af8ce112be6eaf86c6bde311e248b1f601884
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: http://git-master/r/1475902
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Sachin Nikam <snikam@nvidia.com>