rt-patches: delete patch#192 for PASS_LIMIT
After change https://git-master.nvidia.com/r/#/c/1749515/
contents of the patch were empty which caused git am error:
error: cannot read mbox rt-patches/0192-rt-Improve-the-serial-console-PASS_LIMIT.patch
error: cannot split patches from rt-patches/0192-rt-Improve-the-serial-console-PASS_LIMIT.patch

So, delete this patch #192 as the required changes
are merged in mainline kernel with above change.
Basically PASS_LIMIT has same value for both rt and non-rt.

Bug 200408728

Change-Id: I655e2a0f4d371300c09e918376bfe58eb7483c8a
Signed-off-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1774366
GVS: Gerrit_Virtual_Submit
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>