wireless: rtl8822be: Fix build errors of bool-operation
There are build errors when building the driver:
    error: ‘~’ on a boolean expression [-Werror=bool-operation]

So this change just to use "!" instead of "~" to fix them.

Change-Id: Icfa6c38abd5acc36922c926017aaab39adcbf776
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1787894
GVS: Gerrit_Virtual_Submit